"""empty message

Revision ID: abee0b0b7a47
Revises: 84bf80174138
Create Date: 2023-06-20 14:20:29.963857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abee0b0b7a47'
down_revision = '84bf80174138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don_fullname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('don_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('don_email')
        batch_op.drop_column('don_fullname')

    # ### end Alembic commands ###
