"""empty message

Revision ID: fe496948bd9d
Revises: abee0b0b7a47
Create Date: 2023-06-20 14:41:17.933600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe496948bd9d'
down_revision = 'abee0b0b7a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don_refno', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('don_paygate_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('don_paygate_response')
        batch_op.drop_column('don_refno')

    # ### end Alembic commands ###
